### ISSUE TITLE
How can I use this to see if a point is contained in a large geoJSON file without resorting to inefficient linear search?

### ISSUE THREAD

**Issue by Jessers1** [maparoni/GeoJSONKit#16]

**Comment by nighthawk** [comment]
Uh, totally missed this.

This library by itself is just a GeoJSON parser. However, https://github.com/maparoni/GeoJSONKit-Turf builds on this and exposes various tools to facilitate what you're looking for:

- [Simplifying a GeoJSON](https://github.com/maparoni/GeoJSONKit-Turf/blob/65c330fd7f916f9ac6a37a5f1de9d55942eced21/Sources/GeoJSONKitTurf/Simplify.swift#L33)
- [Creating a ConvexHull](https://github.com/maparoni/GeoJSONKit-Turf/blob/main/Sources/GeoJSONKitTurf/ConvexHull.swift#L28)
- [Polygon contains check](https://github.com/maparoni/GeoJSONKit-Turf/blob/65c330fd7f916f9ac6a37a5f1de9d55942eced21/Sources/GeoJSONKitTurf/Turf%2BPolygon.swift#L45)

Say, [Maparoni](https://maparoni.app) allows you to get the country for a dropped pin. It does this by:

1. Pre-processing a very large GeoJSON with polygons of every country by extracting bounding boxes and convex hulls
2. For every country, first check the bounding box, then the convex hull, then lastly the detailed polygon for the `contains` check

This is fast in my testing, e.g., checking the GeoNames database of over 20k cities taking just under 4s on my laptop, including the preprocessing.
